using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace lab3
{
    public partial class Show : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void ButtonAddOrder_Click(object sender, EventArgs e)
        {
            PanelAddOrder.Visible = true;
        }

        protected void ButtonAdd_Click(object sender, EventArgs e)
        {
            SqlDataSourceOrders.Insert();
            GridViewOrders.DataBind();
            TextBoxDescrip.Text = "";
            TextBoxPrice.Text = "";
            PanelAddOrder.Visible = false;
        }

        protected void ButtonCanel_Click(object sender, EventArgs e)
        {
            TextBoxDescrip.Text = "";
            TextBoxPrice.Text = "";
            PanelAddOrder.Visible = false;
        }

        protected void ButtonEditOrder_Click(object sender, EventArgs e)
        {
            if(ButtonEditOrder.Text == "Edit order")
            {
                GridViewOrders.AutoGenerateEditButton = true;
                ButtonEditOrder.Text = "Finish edit order";
            }
            else
            {
                GridViewOrders.AutoGenerateEditButton = false;
                ButtonEditOrder.Text = "Edit order";
            }
        }

        protected void ButtonDeleteOrder_Click(object sender, EventArgs e)
        {
            if(ButtonDeleteOrder.Text == "Delete order")
            {
                GridViewOrders.AutoGenerateDeleteButton = true;
                ButtonDeleteOrder.Text = "Finish delete order";
            }
            else
            {
                GridViewOrders.AutoGenerateDeleteButton = false;
                ButtonDeleteOrder.Text = "Delete order";
            }
        }

        protected void ButtonAddClient_Click(object sender, EventArgs e)
        {
            PanelAddClient.Visible = true;
        }

        protected void ButtonAddC_Click(object sender, EventArgs e)
        {
            SqlDataSourceClients.Insert();
            GridViewClients.DataBind();
            TextBoxSurname.Text = "";
            TextBoxName.Text = "";
            TextBoxPhone.Text = "";
            TextBoxEmail.Text = "";
            TextBoxAdress.Text = "";
            PanelAddClient.Visible = false;
        }

        protected void ButtonCancelC_Click(object sender, EventArgs e)
        {
            TextBoxSurname.Text = "";
            TextBoxName.Text = "";
            TextBoxPhone.Text = "";
            TextBoxEmail.Text = "";
            TextBoxAdress.Text = "";
            PanelAddClient.Visible = false;
        }

        protected void GridViewClients_SelectedIndexChanged(object sender, EventArgs e)
        {
            PanelButOrder.Visible = true;
        }

        protected void ButtonEditClient_Click(object sender, EventArgs e)
        {
            if (ButtonEditClient.Text == "Edit client")
            {
                GridViewClients.AutoGenerateEditButton = true;
                ButtonEditClient.Text = "Finish edit client";
            }
            else
            {
                GridViewClients.AutoGenerateEditButton = false;
                ButtonEditClient.Text = "Edit client";
            }
        }

        protected void ButtonDeleteClient_Click(object sender, EventArgs e)
        {
            if (ButtonDeleteClient.Text == "Delete client")
            {
                GridViewClients.AutoGenerateDeleteButton = true;
                ButtonDeleteClient.Text = "Finish delete client";
            }
            else
            {
                GridViewClients.AutoGenerateDeleteButton = false;
                ButtonDeleteClient.Text = "Delete client";
            }
        }
    }
}